import { NextResponse } from 'next/server';
import { query } from '../../../../lib/supabase';
import { validateAdminToken, unauthorizedResponse } from '../../../../lib/auth';

export const dynamic = 'force-dynamic';

/**
 * Admin-only: Generate a test purchase code for any theme
 * without going through Stripe payment.
 * Used by admin to test themes before listing them to users.
 * 
 * Protected by Supabase JWT token — must be logged in as admin.
 */

function generateRandomCode() {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = 'SP-';
  for (let i = 0; i < 4; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  result += '-';
  for (let i = 0; i < 4; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

export async function POST(request) {
  // --- Admin Auth Check ---
  const authResult = await validateAdminToken(request);
  if (!authResult.valid) {
    return unauthorizedResponse(authResult.error);
  }

  try {
    const body = await request.json();
    const { theme_id } = body;

    if (!theme_id) {
      return NextResponse.json({ error: 'theme_id is required' }, { status: 400 });
    }

    // Verify theme exists
    const themeResult = await query('SELECT * FROM themes WHERE id = $1', [theme_id]);
    if (themeResult.rows.length === 0) {
      return NextResponse.json({ error: 'Theme not found' }, { status: 404 });
    }

    const theme = themeResult.rows[0];

    // Generate unique code
    let code = '';
    let isUnique = false;
    let attempts = 0;

    while (!isUnique && attempts < 10) {
      code = generateRandomCode();
      const checkResult = await query('SELECT id FROM theme_codes WHERE code = $1', [code]);
      if (checkResult.rows.length === 0) isUnique = true;
      attempts++;
    }

    if (!isUnique) {
      return NextResponse.json({ error: 'Failed to generate unique code' }, { status: 500 });
    }

    // Insert with special ADMIN-TEST order prefix so it's traceable
    const adminOrderId = `ADMIN-TEST-${authResult.email}-${Date.now()}`;
    const themeIdsJson = JSON.stringify([theme_id]);

    await query(
      `INSERT INTO theme_codes (code, theme_ids, status, order_id) VALUES ($1, $2, 'unused', $3)`,
      [code, themeIdsJson, adminOrderId]
    );

    console.log(`🔑 Admin test purchase: Code "${code}" generated by ${authResult.email} for theme "${theme.name}"`);

    return NextResponse.json({
      success: true,
      code,
      theme_name: theme.name,
      order_id: adminOrderId,
      generated_by: authResult.email,
    });

  } catch (error) {
    console.error('❌ Admin test purchase error:', error);
    return NextResponse.json({ error: 'Internal server error: ' + error.message }, { status: 500 });
  }
}
